#!/bin/bash

# DEPLOY SURGICAL FORMATTING FIXES TO VPS WORKER
# Boss: Critical production deployment of formatting pipeline fixes

echo "🚨 DEPLOYING SURGICAL FORMATTING FIXES TO PRODUCTION VPS"
echo "Host: 157.254.24.49"
echo "User: lekhi7866"
echo "Path: ~/vps-worker/"

echo ""
echo "📋 FILES THAT NEED TO BE UPDATED ON VPS:"
echo "============================================"
echo "1. ~/vps-worker/services/workflowExecutionService.js"
echo "   - SURGICAL ROUTING: All formats through professional formatter"
echo "   - PROFESSIONAL DEFAULTS: Impact/Tahoma/Georgia fonts"
echo "   - TYPOGRAPHY PREFS: 36pt/12pt/16pt sizing"
echo ""
echo "2. ~/vps-worker/services/exportService.js" 
echo "   - SURGICAL PDF METHOD: generatePDFFromBeautifulContent()"
echo "   - SURGICAL DOCX METHOD: generateDOCXFromBeautifulContent()"
echo "   - CHAPTER EXTRACTION: extractChaptersFromHTML()"
echo ""

echo "🔧 DEPLOYMENT COMMANDS TO RUN:"
echo "============================================"
echo "# 1. SSH to server"
echo "ssh lekhi7866@157.254.24.49"
echo ""
echo "# 2. Navigate to worker directory"  
echo "cd ~/vps-worker/"
echo ""
echo "# 3. Backup current files"
echo "cp services/workflowExecutionService.js services/workflowExecutionService.js.backup_$(date +%Y%m%d_%H%M%S)"
echo "cp services/exportService.js services/exportService.js.backup_$(date +%Y%m%d_%H%M%S)"
echo ""
echo "# 4. Update files (need to transfer from local)"
echo "# CRITICAL: These files contain the surgical formatting fixes"
echo ""
echo "# 5. Use NVM and restart PM2"
echo "source ~/.nvm/nvm.sh"
echo "nvm use v18.20.8"
echo "pm2 restart all"
echo ""
echo "# 6. Verify deployment"
echo "pm2 logs --lines 50"
echo ""

echo "⚠️ CRITICAL: Without deploying these files, the beautiful formatting fixes"
echo "   will NOT work in production. All ebooks will still be ugly!"
echo ""
echo "💀 BOSS, YOU NEED TO:"
echo "   1. SSH to the server manually (password required)" 
echo "   2. Transfer the modified worker files"
echo "   3. Restart PM2 to apply changes"
echo ""
echo "🔥 OR: Give me permission to use scp/rsync to push files directly"

# Show the exact file sizes to verify transfer
echo ""
echo "📊 LOCAL FILE STATUS (what needs to be deployed):"
echo "============================================"
ls -la vps-worker/services/workflowExecutionService.js 2>/dev/null || echo "❌ vps-worker/services/workflowExecutionService.js not found"
ls -la vps-worker/services/exportService.js 2>/dev/null || echo "❌ vps-worker/services/exportService.js not found"
